### ISSUE TITLE
Use strategy compact for static:content:deploy

### ISSUE THREAD

**Issue by pstuifzand** [ByteInternet/hypernode-deploy-configuration#34]
It seems it's not possible to use strategy `compact` instead of `quick` for `static:content:deploy`.

I tried variants based on this, but not seemed to work.

`$configuration->setVariable('static_deploy_options', '-s compact', 'build');`

The thing I could not find was, how to change these arguments

https://github.com/ByteInternet/hypernode-deploy-configuration/blame/master/src/Command/Build/Magento2/SetupStaticContentDeploy.php#L16-L23

**Comment by tdgroot** [comment]
Hi @pstuifzand,

Thanks for your report. While the old deployment tasks are still in this repository, we actually don't use them anymore and only make use of the magento2 recipe from Deployer.

I think setting the option doesn't work, because this setting `static_deploy_options` has only been recently added, so we need to update Deployer within Hypernode Deploy. I'll let you know when that's done!

**Comment by tdgroot** [comment]
We created a new release: https://github.com/ByteInternet/hypernode-deploy/releases/tag/3.5.3

Can you check if it works now?

**Comment by mbm-peter** [comment]
Yes it worked. I now uses the setting for `static_deploy_options` that I provided. Thank you.

**Comment by tdgroot** [comment]
Thanks for letting us know! Closing the issue now :).
